config/routes.rb
Wodlandia::Application.routes.draw do
  get 'photos/:id', to: 'photos#show'
  post 'users/', to: 'clearance/users#create' 
  
  post '/users/:user_id/password', to: 'clearance/passwords#create'

  resources :users do
    resources :posts
  end

  resources :workouts do
    resources :wods
  end

  resources :wods do
    resources :posts
  end  

  resources :wods

  resources :posts

  get 'humanapi/callback', to: 'humanapi#index'
  resources :humanapi


  root to: 'application#index'
end

app/models/wod.rb
class Wod < ActiveRecord::Base
  belongs_to :user
  belongs_to :workout
end

app/controllers/wods_controller.rb
class WodsController < ApplicationController
  before_action :set_wod, only: [:show, :edit, :update, :destroy]

  # GET /wods
  # GET /wods.json
  def index
    @wods = Wod.all
  end

  # GET /wods/1
  # GET /wods/1.json
  def show
    @wod = Wod.find( params[:id] )
    @workout = Workout.find( @wod.workout_id )
  end

  # GET /wods/new
  def new
    @wod = Wod.new
    @workout = Workout.find( params[:workout_id] )
  end

  # GET /wods/1/edit
  def edit
  end

  # POST /wods
  # POST /wods.json
  def create
    @wod = Wod.new(wod_params)
    @wod.user_id = current_user.id

    respond_to do |format|
      if @wod.save
        format.html { redirect_to @wod, notice: 'Wod was successfully created.' }
        format.json { render action: 'show', status: :created, location: @wod }
      else
        format.html { render action: 'new' }
        format.json { render json: @wod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wods/1
  # PATCH/PUT /wods/1.json
  def update
    respond_to do |format|
      if @wod.update(wod_params)
        format.html { redirect_to @wod, notice: 'Wod was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @wod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wods/1
  # DELETE /wods/1.json
  def destroy
    @wod.destroy
    respond_to do |format|
      format.html { redirect_to wods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wod
      @wod = Wod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wod_params
      params.require(:wod).permit( :workout_id )
    end
end

app/views/wods/_form.html.erb
<p><%= @workout.name %></p>
<p><%= @workout.description %></p>
<%= form_for @wod, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.hidden_field :workout_id, :value => @workout.id %>
  <div class="form-actions">
    <%= f.submit "create wod for "+Date.today.strftime('%A, %d %B %Y'), :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                wods_path, :class => 'btn' %>
  </div>
<% end %>

app/views/wods/edit.html.erb
<%- model_class = Wod -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/wods/index.html.erb
<%- model_class = Wod -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @wods.each do |wod| %>
      <tr>
        <td><%= link_to wod.id, wod_path(wod) %></td>
        <td><%= wod.user_id %></td>
        <td><%=l wod.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_wod_path(wod), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      wod_path(wod),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_wod_path,
            :class => 'btn btn-primary' %>

app/views/wods/new.html.erb
<%- model_class = Wod -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/wods/show.html.erb
<%- model_class = Wod -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @wod.user_id %></dd>

  <dt><strong><%= @workout.name %>:</strong></dt>
  <dd><%= @workout.description %></dd>

  <dt><strong>Date:</strong></dt>
  <dd><%= Date.today.strftime('%A, %d %B %Y') %></dd>
</dl>

<div class="form-actions">
  <%= link_to "make a new wod post",
              new_wod_post_path(@wod), :class => 'btn'  %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              wods_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_wod_path(@wod), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              wod_path(@wod),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>